### ISSUE TITLE
Endpoint request validation

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#148]
After merging #128 we'd like to break down the validation code in https://github.com/SmartBear/git-en-boite/blob/main/packages/client-adapter-web/src/intercept_request.ts to be able to compose validation middleware on each end-point instead.

There's a question about whether we want to try and find a Koa plugin or framework.

**Comment by mattwynne** [comment]
@16sheep this looks good:

https://ppeerttu.github.io/koa-req-validation/#koa-req-validation

**Comment by mattwynne** [comment]
I've been playing with koa-req-validation today and it's been getting on my nerves a bit. You have to learn their DSL and I'm not sure it gives us enough over biting the bullet and using JSON schemas and [AJV](https://github.com/ajv-validator/ajv).

This is a good guide: https://spin.atomicobject.com/2018/03/26/typescript-data-validation/

**Comment by mattwynne** [comment]
First attempt in 2d8475d2b1c7a9d3642bbd3589c632c8a95d661d

**Comment by 16sheep** [comment]
> There are also things built around Joi, e.g. https://www.npmjs.com/package/koa-joi-validate

Tried koa-joi-validate,
It looked straight forward enough from the docs but the their version of Joi is out of date and there are problems validating the schema. 

Will go for this as well https://ppeerttu.github.io/koa-req-validation/#koa-req-validation

And then perhaps try Joi out of the box if the above is not nice.

**Comment by mattwynne** [comment]
@16sheep I'm glad you're still chipping away at this.

I tried koa-req-validation already and I didn't like it. See https://github.com/SmartBear/git-en-boite/issues/148#issuecomment-677729699

I have a bias against Joi generally, as it seems to me it's just re-creating JSON Schema, which is already a thing.

What did you learn from the experiment with ts-json-validator?

**Comment by mattwynne** [comment]
My hunch is that [AJV](https://github.com/ajv-validator/ajv) looks really good, and that it would be pretty easy to build our own middleware wrapper around that. The hurdle is learning the json-schema language, but that's a more re-usable skill than learning Joi's API, and from memory it's not that tricky.

**Comment by 16sheep** [comment]
AJV is nice, there are a lot of options and the basics are straight forward
Tried it in [this commit](https://github.com/SmartBear/git-en-boite/commit/5ed0b2252458092c96970e99955f13a4c4fdb391). Still need to extract it, use it everywhere else, remove old validation bits, use ajv ErrorObject params as well as message for more precise feedback and have a second look at parsing of the payload.

**Comment by mattwynne** [comment]
Looks great @16sheep.

I made a couple of comments on the commit.

I like the way you've concatenated the validation errors from AJV into one, and I think we should stop using an error object as the response and just return a string, using `ctx.throw(400, message)`
