### ISSUE TITLE
Validate push authorisation on connect

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#217]
At the moment we use an `ls-remote` call to validate that the token supplied in the Repo URL has sufficient permissions but (see #158) this means it's possible to connect with a token that can only read but not write to a repo.

I think we could do this using the git protocol (as opposed to calling the provider's API) by trying to push to a temporary ref, then deleting it again immediately.

We'd do this as part of the `ValidateRemote` git operation during any `connect` transaction.

**Comment by jbpros** [comment]
@mattwynne I wanted to use custom refs like `refs/git-en-boite/write-access-test-abcdef` to avoid polluting the remote repo with temporary branches but there is a bug in node-git-server that prevents other refs than tags and branches from being pushed, which means this couldn't be TDDed/tested.

I ended up pushing refs like `refs/heads/write-access-test-abcdef`. The branch is deleted immeditately.

**Comment by mattwynne** [comment]
Looks good!

Yeah a custom ref would have been neater; could we have tested it with a regular file-based remote instead of a http one?
