### ISSUE TITLE
Add some smoke test

### ISSUE THREAD

**Issue by cbohiptest** [SmartBear/git-en-boite#249]
In commit https://github.com/SmartBear/git-en-boite/commit/62e0533235987c37a621fd83b83b8e5f1b0c6e02 the tests in the dockerfile are not run anymore to remove the tests files and src from the docker to have a lighter docker. (CI build was running the specs in the docker container as part of the build)

But these tests could be replace a "black box" smoke test on the whole container.

TODO:

- [x] Rewrite tests in TypeScript
- [x] Test commit functionality
- [x] run smoke tests against docker container running on CI server
- [ ] run smoke tests against prod
- [x] use randomly-generated branch name in smoke tests to avoid race conditions between parallel jobs or prod/ci testing running at the same time
- [x] review GH actions job names
- [x] Document smoke tests in README
- [x] Figure out what credentials to use to write to the demo repo.
- [x] Build docker image first and run the tests against that instead of using `docker-compose`?

**Comment by mattwynne** [comment]
I think we should use this as our inspiration, and aim to replace it with what we build here:

https://github.com/SmartBear/git-en-boite-infra/blob/main/bin/smoke

This covers fetching from a remote repo, but it does not cover making a commit at the moment.

**Comment by mattwynne** [comment]
Needed for #250

**Comment by mattwynne** [comment]
It looks like, now that we're starting docker-compose with `--detach` it's just carrying on and running the next step before the server has started.

Maybe the first step of the smoke test is to poll until it's up.

**Comment by mattwynne** [comment]
Ok the build is now green, running the bash smoke test.

The next iteration would be to re-write the bash smoke-test in Typescript.

**Comment by jbpros** [comment]
We're currently building the docker image *after* running the smoke tests against a container brought up by `docker-compose up`. Should we do the opposite instead? Build the real image and run the tests against a container running it? We're basically building everything twice at the moment, if I get this right.

**Comment by jbpros** [comment]
We currenlty use a personnal token from @cbohiptest with full write access to run the tests on CI. This is not ideal but I don't know if we have a test/bot account we could use instead.

Any ideas?

**Comment by jbpros** [comment]
We're now building the image, smoke testing it and then publishing it if the tests succeed. And we don't build twice anymore (we used to, when doing `docker-compose up` for the smoke tests).

Since ad1fb8034adf8bef2f17d308638e581558b94884.

**Comment by jbpros** [comment]
We've switched the personal token from @cbohiptest to @livingdoc-dev (see in LastPass for that account credentials).

**Comment by jbpros** [comment]
We're moving the "run smoke tests against prod" task to a new separate ticket.
