### ISSUE TITLE
Docker image should be clean with only `dist` folders

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#250]
We should remove all the typescript files and only install the `--production` dependencies.

Could [this](https://docs.docker.com/develop/develop-images/multistage-build/) help?

**Comment by mattwynne** [comment]
Interesting problem now with the build:

```
Step 11/13 : RUN yarn tsc --build && rm -rf packages/**/src
 ---> Running in b5b6822bad30
yarn run v1.22.5
$ /app/node_modules/.bin/tsc --build
packages/app/src/features/support/matchers/is_success.ts(1,25): error TS2307: Cannot find module 'hamjest' or its corresponding type declarations.
```

Looks like we'll need to delete all of the `*.spec.ts` files and `apps/src/features` files before we try to build the typescript with only the `--production` dependencies. Maybe we can put this into a `yarn build:something` script so each package is responsible for deleting its own non-production source files? What should we call it?

**Comment by mattwynne** [comment]
I think this is done. @romaingweb is there any more to do to clean up the duplicaiton in the `tsconfig` files? Or shall we make that a separate ticket?

**Comment by romaingweb** [comment]
In the editor, we're ignoring the .spec.* I think when copying files in the image (using the dockerignore).

And yes we could clean up the tsconfig to match what we did in the editor too, and I would do that separately indeed.

**Comment by mattwynne** [comment]
Yeah the spec files are being removed now - we have to so that the typescript will compile without those --production dependencies.

I'll close this then and we can de-dupe the tsconfigs another time.
