### ISSUE TITLE
Move to yarn 2

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#251]
https://dev.to/arcanis/introducing-yarn-2-4eh1

**Comment by jbpros** [comment]
looks pretty cool -- workspaces getting a lot of love :D

**Comment by jbpros** [comment]
What do we thing about [zero-installs](https://next.yarnpkg.com/features/zero-installs)?

**Comment by mattwynne** [comment]
Interesting! I'm willing to try it. It seems well thought out, though TBH it seems to solve a problem I don't remember having since `yarn.lock` came along.

**Comment by mattwynne** [comment]
It says [here](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem) that dependabot only supports yarn v1 which I think probabably kills this idea for now.

**Comment by jbpros** [comment]
oh well

**Comment by mattwynne** [comment]
Are you sad?

**Comment by jbpros** [comment]
Haha no. A bit disappointed. Yarn 2 has got amazing features but it seems tough to migrate existing projects.

I'm also not convinced by the approach they took with this `set version` business. Why not go with a non-backward compatible yarn2? I don't see what's good about that half-arsed design decision. It is confusing, overly complicated and you need to understand a lot of what's under the hood. Something I liked about yarn was its simplicity. It now seems they have fallen into the trap of most JS ecosystem tools (think webpack, babel, etc) where you need to understand a million things, configure stuff all over the place just to get the most banal stuff working.

I imagine being a newcomer to JS/TS, being told to use yarn and feeling absolutely overwhelmed by the tool. In the end, this feels like a step backwards, raising the barrier to entry, again.

Maybe on a brand new project it is all fine. But after failing to migrate two TS projects, my enthusiasm for it has been seriously broached.
