### ISSUE TITLE
Rename "GitRepo" to "LocalClone"

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#254]
That name better represents the role that this plays from the Repo's point of view.

See https://twitter.com/mattwynne/status/1313519048458731521

**Comment by mattwynne** [comment]
What a difference a rename makes.

Thanks for the counsel @mathiasverraes!

**Comment by mathiasverraes** [comment]
Anytime 😊

**Comment by romaingweb** [comment]
Excellent! I love it.
