### ISSUE TITLE
Some errors are logged without message or stack properties

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#328]
Here's some examples from DataDog:

* [a `GitCommandError` logged by a worker](https://app.datadoghq.com/logs?cols=host%2Cservice%2Ccontainer_name&event=AQAAAXW4GEPA2FpocAAAAABBWFc0R0ZCX0FBQlozVXVYekR0S1VBQUI&from_ts=1605109111618&index=&live=true&messageDisplay=inline&query=service%3A%28git-en-boite+OR+gherkin-editor%29&stream_sort=desc&to_ts=1605112711618)
* [a `TypeError` loggeed by the server (when trying to deserialize the error above!)](https://app.datadoghq.com/logs?cols=host%2Cservice%2Ccontainer_name&context_event=AQAAAXW4GEZZN3mpkAAAAABBWFc0R0VtQ0FBREI0Z0pJOXZPYXd3QUI&event=&from_ts=1605109111645&index=&live=false&messageDisplay=inline&query=host%3Ai-07327664f8bb84545+service%3Agit-en-boite+container_id%3Afe59effa36915493e226919502531cb20c988b8b82f0d8e2bb42cf494eb580e7+filename%3A0.log&saved_view&stream_sort=desc&to_event=AQAAAXW4GEZZN3mpkAAAAABBWFc0R0VtQ0FBREI0Z0pJOXZPYXd3QUI&to_ts=1605111400026)

I've debugged it, and it seems that the error objects somehow don't `JSON.stringify` those properties. I've tried to create objects like that in the tests for `createLogger` but I can't reproduce an object like that in a test.

**Comment by jbpros** [comment]
We've tested this manually, errors seem to be logged properly now.
