### ISSUE TITLE
Use proper 2xx HTTP codes on connect

### ISSUE THREAD

**Issue by jbpros** [SmartBear/git-en-boite#334]
We currently use a redirect (`30x`) HTTP status code on a _connect_ request for a repo that was already connected. I believe this is an odd use of a redirect status. The 3xx (Redirection) class of status code [indicates that further action needs to be taken by the user agent in order to fulfill the request](https://tools.ietf.org/html/rfc7231#section-6.4). In the case of a _connect_ request on git-en-boîte for an already connected repo, the client is not expected to take any further action to connect the repo.

I'm unclear as to why we need to tell the client about the internal differences: does it matter if the repo was already connected or not? 

If it does, then I suggest we use `201 Created` as the status for a _connect_ that succeeded and actually connected a new repo, `200 OK` for a successful _connect_ for an existing repo.

If it does not matter, then we just return `200 OK` on all successful _connects_ (this has my preference for now, but I might be missing a good reason for the differentiation). 

We'll need to adapt `Git::GitEnBoite` in CucumberStudio when we make this change.

Checklist:

- [ ] Decide if we want different statuses for new/existing repos.
- [ ] Get rid of the redirect and use 20x statuses.
- [x] Adapt CucumberStudio's `Git::GitEnBoite.connect`
- [x] POST to `/repos/:repoId`

**Comment by mattwynne** [comment]
Agreed. I think we should also return a location header with the location of the newly created resource.

Arguably, if we already know the `repoId` we should be POSTing directly to `/repos/:repoId` to create it.

**Comment by mattwynne** [comment]
IMO on the 201/200 I'm not sure I see a reason yet why a client would need it, but on the other hand it's good to be communicative if we have that information to hand.

**Comment by jbpros** [comment]
´Location’ is to be used with [3xx and 201](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location) is limited is highly focussed on automatic redirection. [Link](https://tools.ietf.org/html/rfc5988) headers are a good fit for telling the client about related resources (like the related repo, or its branches or whatever relevant stuff). It is typically used in [HATEOAS](https://en.m.wikipedia.org/wiki/HATEOAS) systems. Hypermedia has many great advantages, especially for public facing APIs like Git-en-Boîte (one of them is virtually no need for API versioning).

**Comment by jbpros** [comment]
I agree about the post request to a specific endpoint for the known repo ID.

**Comment by mattwynne** [comment]
💯 on the HATEOS thing. Let's do that before we add any more end-points.

**Comment by mattwynne** [comment]
bump

**Comment by mattwynne** [comment]
We're working on this code now as part of https://github.com/hiptest/cucumberstudio/issues/1434 I suggest we take the opportunity to clean it up a little.

I would starty by changing this line to send a `PUT` request to `/repos/{repoId}`:

https://github.com/SmartBear/git-en-boite/blob/ec0ffa956ec017aa56fc452bd0298f5cb77b8817/packages/acceptance-tests/src/step_definitions/steps.ts#L79

That can then drive a change to this unit test for the router/controller:

https://github.com/SmartBear/git-en-boite/blob/main/packages/web/src/routes/repos/update.spec.ts#L30

It should be changed to behave more like this endpoint:

https://github.com/SmartBear/git-en-boite/blob/main/packages/web/src/routes/repos/create.spec.ts#L41

We can be confident about changing the `/repos/{repoId}` endpoint - the only production client we have is CucumberStudio at the moment, which uses the [`POST /repos` endpoint](https://github.com/hiptest/cucumberstudio/blob/master/lib/git/git_en_boite.rb#L30) so as long as we leave that alone we won't break anything.

**Comment by jbpros** [comment]
> It should also be changed to update the repo if it already exists, with the new `repoId`.

Do you mean the new `repoUrl`?

**Comment by mattwynne** [comment]
> Do you mean the new repoUrl?

Yes! I've updated the comment for clarity.

**Comment by mattwynne** [comment]
@jbpros I think this is done in 57aaa63. I kept the `POST /repos` endpoint but if you post here now, you just pass the `remoteUrl` and it will generate a `repoId` for you, then pass you back the URL in the Link header. I used the `item` rel for this. WDYT?
