### ISSUE TITLE
Allow clients to update remoteUrl for a repo

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#545]
Add an endpoint at `PUT /repos/:repoId`

**Comment by mattwynne** [comment]
fdbca262de7e9c804f77ef4f2f360bc57610beb7

**Comment by mattwynne** [comment]
We need to change this line:

https://github.com/SmartBear/git-en-boite/blob/main/packages/app/src/la_bo%C3%AEte.ts#L40

...so that it will find or create the repo, then call `setOriginTo` on it.

**Comment by romaingweb** [comment]
Done in 8a7c940
