### ISSUE TITLE
Failed to save a feature when the local repo is not up to date

### ISSUE THREAD

**Issue by cbohiptest** [SmartBear/git-en-boite#566]
When using the gherkin editor in Cucumber Studio, if a change is made to the repository in GitHub from GitHub it becomes impossible to save from a new feature from Cucumber Studio.

An error is raised from GitEnBoite : 

To https://github.com/cbohiptest/coffee-machine.git
 ! [rejected]        refs/pending-commits/main-d3db90cc-ac8d-4709-9363-de28d0d88a37 -> main (non-fast-forward)
error: failed to push some refs to 'https://421fc37d4b7ebd75ddaee3bb8e3388bcad1fc5b6@github.com/cbohiptest/coffee-machine.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

https://app.datadoghq.com/logs?event=AQAAAXftBmW11u8UcgAAAABBWGZ0Qm5HNkFBQ0ZDM3RtR0c4VTBRQUE&from_ts=1614587748909&index=%2A&live=true&query=status%3Aerror&to_ts=1614591348909

Maybe GitEnBoite should do a pull --rebase before pushing to be up to date with the remote repository.

**Comment by mattwynne** [comment]
My bad [I removed this](https://github.com/SmartBear/gherkin-editor/commit/b708533f1b2d3a3cc892585b6703660a877392e2#diff-e1f65451b2dcf0c1435c4257f04d4c33a2046e2826d6af621b12459c75bfc3a6) from the old calls to the GitProvider API and didn't [replace it](https://github.com/SmartBear/gherkin-editor/blob/main/packages/git/src/GitDocumentStore/GitDocumentStoreSession.ts#L28) in the new DocumentStore.

**Comment by mattwynne** [comment]
I totally agree that it's better for git-en-boite to be responsible for this 👍

**Comment by mattwynne** [comment]
Fixed in 434b9c8739902985b51d6c2e046850d59d61aef8
