### ISSUE TITLE
Smoke tests don't seem to wait for initial background fetch

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#571]
We've had a problem deployng recently where the smoke tests are failing. It seems like they're rushing ahead beyond the step `it "Waits for repo to be fetched"` instead of syncing at that point.

In fact, we can see this is probably true because the next check, which reflects on the branch info [expects there to be no branches](https://github.com/SmartBear/git-en-boite/blob/main/packages/smoke-tests/index.ts#L83) when in fact there are loads in that repo.

**Comment by mattwynne** [comment]
I've done some investigation and introduced a deliberate 10-second sleep where the sync on the `repo.fetched` event is supposed to happen. This caused the list of branches to be populated so the next step failed.

**Comment by mattwynne** [comment]
69d1a9238b146f7e7af4062f4e6328cdbdc4288d should resolve this.

**Comment by mattwynne** [comment]
Ok the container with this change in it has sailed through the deploy so I think this is fixed.

@romaingweb there was nothing wrong with your change at all, it just exposed a problem that had been there all along in the smoke tests.

**Comment by romaingweb** [comment]
@mattwynne Amazing! So just getting the response is not enough because the promise is still somewhat unresolved?

**Comment by mattwynne** [comment]
My guess is that, because it's a long-running SSE connection, the promise on the `fetch` call gets you the open response, but the promise on the body is what gets you the sync on the response being closed by the server.
