### ISSUE TITLE
Handle failures when connecting a repo

### ISSUE THREAD

**Issue by mattwynne** [SmartBear/git-en-boite#79]

**Comment by aurelien-reeves** [comment]
Proposition:
- fail fast sync: check the URL, the credentials/token, and make sure we have all what is required to clone repos
- do the clone async unless we find a way to clone it that will always be quick even with big repos

**Comment by mattwynne** [comment]
We could use `git ls-remote` to validate the remote URL & credentials before doing a fetch.

**Comment by aurelien-reeves** [comment]
`git clone https://github.com/cucumber-school/bdd-with-cucumber.git --depth=1 --bare`

**Comment by mattwynne** [comment]
By splitting up the `Connect` from `Fetch`, and giving immediate feedback when trying to connect a bad URL, we're done with this.

When we do #26 we'll need to start feedback back specific messages about what's wrong with the user's request when they try to connect a new repo.

We'll use #99 to track the work to make the Fetch happen in an eventually-consistent manner.
