### ISSUE TITLE
Git requesting auth on the server's console

### ISSUE THREAD

**Issue by aurelien-reeves** [SmartBear/git-en-boite#90]
When cloning a private repo without any token, or a github repo wich does not exists, the server's console is requesting for git credentials

We should in any case prevent git requesting anything from the command line

**Comment by mattwynne** [comment]
https://git-scm.com/docs/gitcredentials may be relevant.

**Comment by aurelien-reeves** [comment]
Should be fixed thanks to 9e6afed260f93ee827d39c897f343fa6e688322f
But the ValidateRemote.url is the only command for now that prevent requesting credentials. Is that enough?

**Comment by mattwynne** [comment]
Yes, we should move these environment variables down into [`GitDirectory#execGit`](https://github.com/SmartBear/git-en-boite/blob/main/packages/git-adapter/src/git_directory.ts#L10) so we never, ever see these prompts.
